# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"
# Inserts a blank line between shell prompts
add_newline = false
format = '$username$hostname\[$directory\] $character'
right_format = "$all"

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character]  # The name of the module we are configuring is 'character'
success_symbol = "[âœ](bold green)"  # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = "[âœ](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
symbol = "ó°— "
disabled = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"

[hostname]
format = "[$ssh_symbol$hostname]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "ğŸ’¥"
ahead = "â¬†ï¸ ${count}"
behind = "â¬‡ï¸ ${count}"
diverged = "ğŸ”€"
untracked = "ğŸ†•"
stashed = "ğŸ“¦"
modified = "âœï¸"
staged = "â•"
renamed = "ğŸ”"
deleted = "ğŸ—‘ï¸"

[golang]
symbol = "î˜§ "

[aws]
symbol = "ï‰° "

[bun]
symbol = "î¯ "

[c]
symbol = "î˜ "

[cpp]
symbol = "î˜ "

[cmake]
symbol = "î” "

[dart]
symbol = "î˜ "

[deno]
symbol = "îŸ€ "

[docker_context]
symbol = "î° "

[gcloud]
symbol = "îŸ± "

[git_branch]
symbol = "îœ¥ "

[kotlin]
symbol = "î˜´ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ó°› "

[nodejs]
symbol = "îœ˜ "

[os.symbols]
Android = "ï…» "
Debian = "î½ "
Fedora = "îŸ™ "
Redhat = "î½ "
RedHatEnterprise = "î½ "
Ubuntu = "î¯‰ "
Windows = "ó°² "

[python]
symbol = "îœ¼ "

[zig]
symbol = "îš© "
